create exceptions
AY2223S1-CS2113-F11-3/tp pull request #82
Opened 2022-10-19 12:27 UTC by CheahHaoYi

Refactor exceptions
Move some command class to exception

2022-10-19 12:55 UTC, amitrahman1026 commented on src/main/java/seedu/duke/exceptions/InvalidModuleException.java
> +
may use a multi line string instead of concatenating

2022-10-21 12:36 UTC, amitrahman1026 requested changes

2022-10-21 12:36 UTC, amitrahman1026 commented on src/main/java/seedu/duke/parser/Parser.java
> +                case (SearchModuleCommand.COMMAND_WORD):
switch - case should be alinged for coding standard

2022-10-21 13:38 UTC, amitrahman1026 submitted a review, later dismissed

2022-10-21 13:59 UTC, amitrahman1026 approved these changes
lgtm

2022-10-21 13:59 UTC, merged

2022-10-22 07:56 UTC, CheahHaoYi commented
Fix #79